// Generated by sqlboiler-erg: DO NOT EDIT.

{{- range $e := .Enums }}
export enum {{ .Name.PascalCase }} {
{{- range $value := .Values }}
    {{ .Label }} = {{ doubleQuotesToSingleQuote .Value }},
{{- end }}
}
{{- end }}

{{- range $table := .Tables }}
export interface {{ .Name.PascalCase }}Relations {
{{- range $relation := .Relations }}
    {{ getTypescriptType .Type .Name}};
{{- end }}
}

export interface {{ .Name.PascalCase }} extends {{ .Name.PascalCase }}Relations {
{{- range $column := .Columns }}
    {{ getTypescriptType .Type .Name}};
{{- end }}
}
{{- end }}