// Generated by sqlboiler-erg: DO NOT EDIT.

{{- range $e := .Enums }}
export enum {{ .Name.PascalCase }} {
{{- range $value := .Values }}
  {{ .Label }} = {{ .Value }},
{{- end }}
}

{{- end }}

{{- range $table := .Tables }}
export interface {{ .Name.PascalCase }} {
{{- range $column := .Columns }}
  {{ getTypescriptType .Type .Name.SnakeCase}};
{{- end }}

{{- range $relation := .Relations }}
  {{ getTypescriptType .Type .Name.SnakeCase}};
{{- end }}

  custom_fields?: Record<string, any>
}
{{- end }}