// Code generated by SQLBoiler 4.17.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dm

var TableNames = struct {
	Account          string
	Causer           string
	SchemaMigrations string
	SystemAccount    string
}{
	Account:          "account",
	Causer:           "causer",
	SchemaMigrations: "schema_migrations",
	SystemAccount:    "system_account",
}
